name: quiz_quest
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.3
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  dio: ^5.4.0
  bloc: ^8.1.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.3
  circular_countdown_timer: ^0.2.3
  firebase_auth: ^4.16.0
  image_picker: ^1.0.7
  firebase_storage: ^11.6.0
  share_plus: ^7.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.5


flutter:

  
  uses-material-design: true
  assets: 
    - images/

 